# Generated by Django 5.1.1 on 2024-09-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
